name: ci

on:
  push:
    branches:
    - 'main'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@hiep/default-registry
    with:
     install-dependencies-command: 'sudo apt-get install libzmq3-dev'
     run-unit-tests: true
     run-integration-tests: true
     run-lint: true
     run-build: true
     run-gosec: true
     gosec-args: "-no-fail ./..."
     
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/default-registry
    secrets: inherit
    with:
     publish: false
